#!/bin/bash
# =============================================================================
# Battles Record - Docker Entrypoint
# =============================================================================
# Generates br-config.toml from environment variables, then starts the daemon.

set -e

CONFIG_FILE="/config/br-config.toml"

# =============================================================================
# Required variables (fail fast if missing)
# =============================================================================
: "${BR_ADMIN_USERNAME:?BR_ADMIN_USERNAME is required}"
: "${BR_ADMIN_PASSWORD:?BR_ADMIN_PASSWORD is required}"
: "${BR_JWT_SECRET:?BR_JWT_SECRET is required}"

# =============================================================================
# Default values
# =============================================================================

# Daemon
BR_HOST="${BR_HOST:-0.0.0.0}"
# Note: Port is always 8080 inside the container. Use docker-compose ports mapping
# to expose on a different host port (e.g., "8081:8080")
BR_LOG_LEVEL="${BR_LOG_LEVEL:-info}"
# Channels are stored in a separate TOML file that persists across container restarts
BR_CHANNELS_FILE="${BR_CHANNELS_FILE:-/config/channels.toml}"

# Storage
BR_RECORDINGS_DIR="${BR_RECORDINGS_DIR:-/data/recordings}"
BR_LIBRARY_DIR="${BR_LIBRARY_DIR:-/data/library}"
BR_IMAGES_DIR="${BR_IMAGES_DIR:-/data/images}"
BR_DISK_WARNING_THRESHOLD="${BR_DISK_WARNING_THRESHOLD:-90}"

# Jellyfin integration
BR_JELLYFIN_ENABLED="${BR_JELLYFIN_ENABLED:-false}"
BR_JELLYFIN_FETCH_IMAGES="${BR_JELLYFIN_FETCH_IMAGES:-true}"
BR_JELLYFIN_GENERATE_THUMBNAILS="${BR_JELLYFIN_GENERATE_THUMBNAILS:-true}"

# Post-processing
BR_PP_ENABLED="${BR_PP_ENABLED:-true}"
BR_PP_OUTPUT_FORMAT="${BR_PP_OUTPUT_FORMAT:-mp4_reencode}"
BR_PP_SEGMENT_HANDLING="${BR_PP_SEGMENT_HANDLING:-delete}"
BR_PP_MAX_CONCURRENT="${BR_PP_MAX_CONCURRENT:-2}"
BR_PP_CRF="${BR_PP_CRF:-20}"
BR_PP_PRESET="${BR_PP_PRESET:-medium}"
BR_PP_VIDEO_CODEC="${BR_PP_VIDEO_CODEC:-libx264}"
BR_PP_AUDIO_CODEC="${BR_PP_AUDIO_CODEC:-aac}"
BR_PP_AUDIO_BITRATE="${BR_PP_AUDIO_BITRATE:-128k}"

# =============================================================================
# Hash the admin password
# =============================================================================
echo "Hashing admin password..."
ADMIN_HASH=$(br-daemon --hash-password "$BR_ADMIN_PASSWORD")

# =============================================================================
# Generate config file
# =============================================================================
echo "Generating config at $CONFIG_FILE..."

cat > "$CONFIG_FILE" << EOF
# Auto-generated by docker-entrypoint.sh
# Do not edit manually - changes will be overwritten on container restart

[daemon]
host = "$BR_HOST"
port = 8080
log_level = "$BR_LOG_LEVEL"
channels_file = "$BR_CHANNELS_FILE"

[auth]
jwt_secret = "$BR_JWT_SECRET"

[[users]]
username = "$BR_ADMIN_USERNAME"
password_hash = "$ADMIN_HASH"
role = "admin"

[storage]
recordings_dir = "$BR_RECORDINGS_DIR"
library_dir = "$BR_LIBRARY_DIR"
images_dir = "$BR_IMAGES_DIR"
disk_warning_threshold = $BR_DISK_WARNING_THRESHOLD

[jellyfin]
enabled = $BR_JELLYFIN_ENABLED
fetch_profile_images = $BR_JELLYFIN_FETCH_IMAGES
generate_thumbnails = $BR_JELLYFIN_GENERATE_THUMBNAILS

[post_processing]
enabled = $BR_PP_ENABLED
output_format = "$BR_PP_OUTPUT_FORMAT"
segment_handling = "$BR_PP_SEGMENT_HANDLING"
max_concurrent = $BR_PP_MAX_CONCURRENT

[post_processing.encoding]
crf = $BR_PP_CRF
preset = "$BR_PP_PRESET"
video_codec = "$BR_PP_VIDEO_CODEC"
audio_codec = "$BR_PP_AUDIO_CODEC"
audio_bitrate = "$BR_PP_AUDIO_BITRATE"
EOF

# =============================================================================
# Platform authentication (optional)
# =============================================================================

if [ -n "$BR_TWITCH_ACCESS_TOKEN" ]; then
cat >> "$CONFIG_FILE" << EOF

[platform_auth.twitch]
access_token = "$BR_TWITCH_ACCESS_TOKEN"
EOF
  [ -n "$BR_TWITCH_REFRESH_TOKEN" ] && echo "refresh_token = \"$BR_TWITCH_REFRESH_TOKEN\"" >> "$CONFIG_FILE"
  [ -n "$BR_TWITCH_USERNAME" ] && echo "username = \"$BR_TWITCH_USERNAME\"" >> "$CONFIG_FILE"
  echo "  -> Twitch auth configured"
fi

if [ -n "$BR_YOUTUBE_ACCESS_TOKEN" ]; then
cat >> "$CONFIG_FILE" << EOF

[platform_auth.youtube]
access_token = "$BR_YOUTUBE_ACCESS_TOKEN"
EOF
  [ -n "$BR_YOUTUBE_REFRESH_TOKEN" ] && echo "refresh_token = \"$BR_YOUTUBE_REFRESH_TOKEN\"" >> "$CONFIG_FILE"
  [ -n "$BR_YOUTUBE_USERNAME" ] && echo "username = \"$BR_YOUTUBE_USERNAME\"" >> "$CONFIG_FILE"
  echo "  -> YouTube auth configured"
fi

if [ -n "$BR_KICK_ACCESS_TOKEN" ]; then
cat >> "$CONFIG_FILE" << EOF

[platform_auth.kick]
access_token = "$BR_KICK_ACCESS_TOKEN"
EOF
  [ -n "$BR_KICK_REFRESH_TOKEN" ] && echo "refresh_token = \"$BR_KICK_REFRESH_TOKEN\"" >> "$CONFIG_FILE"
  [ -n "$BR_KICK_USERNAME" ] && echo "username = \"$BR_KICK_USERNAME\"" >> "$CONFIG_FILE"
  echo "  -> Kick auth configured"
fi

# =============================================================================
# OAuth configuration (optional - for OAuth login flow)
# =============================================================================

if [ -n "$BR_OAUTH_TWITCH_CLIENT_ID" ]; then
cat >> "$CONFIG_FILE" << EOF

[oauth.twitch]
client_id = "$BR_OAUTH_TWITCH_CLIENT_ID"
EOF
  [ -n "$BR_OAUTH_TWITCH_CLIENT_SECRET" ] && echo "client_secret = \"$BR_OAUTH_TWITCH_CLIENT_SECRET\"" >> "$CONFIG_FILE"
  [ -n "$BR_OAUTH_TWITCH_REDIRECT_URI" ] && echo "redirect_uri = \"$BR_OAUTH_TWITCH_REDIRECT_URI\"" >> "$CONFIG_FILE"
  echo "  -> Twitch OAuth configured"
fi

if [ -n "$BR_OAUTH_YOUTUBE_CLIENT_ID" ]; then
cat >> "$CONFIG_FILE" << EOF

[oauth.youtube]
client_id = "$BR_OAUTH_YOUTUBE_CLIENT_ID"
EOF
  [ -n "$BR_OAUTH_YOUTUBE_CLIENT_SECRET" ] && echo "client_secret = \"$BR_OAUTH_YOUTUBE_CLIENT_SECRET\"" >> "$CONFIG_FILE"
  [ -n "$BR_OAUTH_YOUTUBE_REDIRECT_URI" ] && echo "redirect_uri = \"$BR_OAUTH_YOUTUBE_REDIRECT_URI\"" >> "$CONFIG_FILE"
  echo "  -> YouTube OAuth configured"
fi

if [ -n "$BR_OAUTH_KICK_CLIENT_ID" ]; then
cat >> "$CONFIG_FILE" << EOF

[oauth.kick]
client_id = "$BR_OAUTH_KICK_CLIENT_ID"
EOF
  [ -n "$BR_OAUTH_KICK_CLIENT_SECRET" ] && echo "client_secret = \"$BR_OAUTH_KICK_CLIENT_SECRET\"" >> "$CONFIG_FILE"
  [ -n "$BR_OAUTH_KICK_REDIRECT_URI" ] && echo "redirect_uri = \"$BR_OAUTH_KICK_REDIRECT_URI\"" >> "$CONFIG_FILE"
  echo "  -> Kick OAuth configured"
fi

# =============================================================================
# Notifications (optional)
# =============================================================================

if [ -n "$BR_DISCORD_WEBHOOK_URL" ]; then
cat >> "$CONFIG_FILE" << EOF

[notifications.discord]
webhook_url = "$BR_DISCORD_WEBHOOK_URL"
on_stream_start = ${BR_DISCORD_ON_START:-true}
on_stream_end = ${BR_DISCORD_ON_END:-true}
on_error = ${BR_DISCORD_ON_ERROR:-false}
EOF
  echo "  -> Discord notifications configured"
fi

if [ -n "$BR_TELEGRAM_BOT_TOKEN" ] && [ -n "$BR_TELEGRAM_CHAT_ID" ]; then
cat >> "$CONFIG_FILE" << EOF

[notifications.telegram]
bot_token = "$BR_TELEGRAM_BOT_TOKEN"
chat_id = "$BR_TELEGRAM_CHAT_ID"
on_stream_start = ${BR_TELEGRAM_ON_START:-true}
on_stream_end = ${BR_TELEGRAM_ON_END:-true}
on_error = ${BR_TELEGRAM_ON_ERROR:-false}
EOF
  echo "  -> Telegram notifications configured"
fi

if [ -n "$BR_WEBHOOK_URL" ]; then
cat >> "$CONFIG_FILE" << EOF

[notifications.webhook]
url = "$BR_WEBHOOK_URL"
on_stream_start = ${BR_WEBHOOK_ON_START:-true}
on_stream_end = ${BR_WEBHOOK_ON_END:-true}
on_error = ${BR_WEBHOOK_ON_ERROR:-false}
EOF
  echo "  -> Webhook notifications configured"
fi

# =============================================================================
# Start the daemon
# =============================================================================
echo "Starting br-daemon..."
exec br-daemon --config "$CONFIG_FILE"
